name: quarto-python
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.1.2
  - click=8.1.7
  - python=3.11
  - pandas=2.1.2
  - vl-convert-python=1.0.1
  - tabulate=0.9.0
  - tabulate
  - quarto=1.5.57
  - conda (version 23.9.0 or higher)
  - conda-lock (version 2.5.7 or higher)